source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

gem "rails", "~> 7.0.4"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "importmap-rails"
# gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem 'bootsnap', require: false

gem 'omniauth'
gem 'omniauth-oauth2'
gem "omniauth-rails_csrf_protection"

gem 'devise'
gem 'pry'
